name: Build and Test

on:
  push:
    branches:
      - main  # Puedes ajustar esto según la rama que te interese

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Test
        run: |
          ./mvnw clean compile test
